### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by stefanocudini** [Keplerjs/Kepler#10]
**Opened this issue for discus about resources and libraries requirements in the system to install and running smoothly KeplerJS**

**Comment by hitaspdotnet** [comment]
Please update system requirements 
I have installed Meteor and NPM 6.2.0 and Python 2.7.4 but I can't build the project

**Comment by stefanocudini** [comment]
welcome @hitaspdotnet 
what version of Meteor? and MongoDB?
Python is not required

Can you paste the console error output?

**Comment by hitaspdotnet** [comment]
Hi @stefanocudini 

> Python is not required 

It's required by node-gyp

> what version of Meteor? and MongoDB?

MongoDB 4.0 CE
Meteor 1.7 
Node.JS 10.7

```
PS D:\Hitasp Solutions\Kepler> npm install
npm WARN deprecated bcrypt@1.0.3: bcrypt < v2.0.0 is susceptible to bcrypt wrap-around bug. Upgrade to bcrypt >= v2.0.0 for improved support for newer bcrypt hashes

> bcrypt@1.0.3 install D:\Hitasp Solutions\Kepler\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@10.7.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@10.7.0 (node-v64 ABI) (falling back to source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: You must run `node-gyp configure` first!
gyp ERR! stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:53:20)
gyp ERR! stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
gyp ERR! stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:242:13)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\Hitasp Solutions\\Kepler\\node_modules\\bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=D:\\Hitasp Solutions\\Kepler\\node_modules\\bcrypt\\lib\\binding"
gyp ERR! cwd D:\Hitasp Solutions\Kepler\node_modules\bcrypt
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\Hitasp Solutions\Kepler\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=D:\Hitasp Solutions\Kepler\node_modules\bcrypt\lib\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Hitasp Solutions\Kepler\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Hitasp Solutions\\Kepler\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\Hitasp Solutions\Kepler\node_modules\bcrypt
node-pre-gyp ERR! node -v v10.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\Hitasp Solutions\Kepler\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=D:\Hitasp Solutions\Kepler\node_modules\bcrypt\lib\binding' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by hitaspdotnet** [comment]
https://github.com/kelektiv/node.bcrypt.js/issues/590

**Comment by hitaspdotnet** [comment]
Why we need to use `bcrypt@1.0.3` with the latest version of NodeJs?

**Comment by stefanocudini** [comment]
@hitaspdotnet from Meteor version 1.4 it's use bcrypt for storing the passwords:
https://docs.meteor.com/changelog.html#v14120160818

however I'm trying to find a way to remove the python dependecy, which seems to me a very uncomfortable thing :( you're right

we will find a solution together

**Comment by hitaspdotnet** [comment]
@stefanocudini So I need to downgrade Meteor to 1.4 version? What's recommended version of requirements libs to get available to run Kepler?

**Comment by stefanocudini** [comment]
I have not tested any newer versions yet 1.5:
https://github.com/Keplerjs/Kepler/blob/master/.meteor/release
I don't think there will be problems for more recent versions, but the problem could be persist because the dep bcrypt isn't required from Kepler but from Meteor.. :(

however, usually in a python development and production environment it is always present .. it is not such a strange dependency, what OS are you using for the deployment of Kepler?

**Comment by hitaspdotnet** [comment]
@stefanocudini I haven't a problem with python, my problem is Kepler need the `bcrypt@1.0.3` but this can't be installed with node 10.7.
I tried to upgrade `bcrypt` I got more environment error. My question is "Why Kepler Docs recommended us to use the latest version of NodeJs but Kepler's libraries depended on the previous versions? And what we need for building Kepler on our local machine? "

**Comment by stefanocudini** [comment]
@hitaspdotnet I just tested Kepler with nodejs v 10.6.0 and updated bcrypt to v2.0.1

pull and test! please

**Comment by hitaspdotnet** [comment]
@stefanocudini Thanks.

**Comment by stefanocudini** [comment]
@hitaspdotnet now it works? "Is very important for me this.

for more infomation you can see the official docs here:
http://docs.keplerjs.io/quick-start.html

and for deploy kepllerjs in a production environment here:
http://docs.keplerjs.io/deployment.html

the documentation is still very basic, consider hypotheses to help me complete it .. it would be a great help for the project, it's simple fork and edit md files inside docs directory here:
https://github.com/keplerjs/docs

**Comment by hitaspdotnet** [comment]
@stefanocudini Everythings works well. Thanks in advance.

> the documentation is still very basic, consider hypotheses to help me complete it

My English is bad, so I can open a new issue for missed sections

**Comment by stefanocudini** [comment]
Ok or you consider to contribute for translations.. is very simple in kepler, see it for an exmaple:
https://github.com/Keplerjs/Kepler/pull/3
