### ISSUE TITLE
lines and polygons

### ISSUE THREAD

**Issue by caduguedess** [Keplerjs/Kepler#80]
I would like to know if it can handle other geometry data than points. For example lines and polygons.
If so, does it support geographic data formats like GeoJSON, shapefile or KML?
Thanks

**Comment by stefanocudini** [comment]
For now the plugin [kepler import](https://github.com/Keplerjs/Kepler/tree/master/packages/import) support only GeoJSON file format having **points** inside(a feature collection of points).
Some of this Point properties is imported like a [Kepler.Place](https://docs.keplerjs.io/models.html) for example _name, url_.. other properties is ignored.
https://github.com/Keplerjs/Kepler/blob/master/packages/import/server/Import.js#L4

Currently(**v1.6.6**) the kepler data model provides a generic geometry field in addition to the LOC field which represents only one point. but it is not used by the import plugin
with some minor modifications this would be possible.

The import plugin is actually works for geojson file only by admin users.
Only if you login as an admin user in kepler you can see in your user panel in the ADMIN section an IMPORT DATA to access the data import panel which allows you to upload files.
how you can see here:
![import-name](https://user-images.githubusercontent.com/47107/58631523-1f8c8280-82e3-11e9-8a92-24533d1c6a61.gif)

**Comment by stefanocudini** [comment]
hi @caduguedess new version of KeplerJS is out 1.7.0

now kepler support imports geojson with any type of geometry
